# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0fd658518bddd1dc46f98cdb1093fce0"
name = "hide-payment-by-product-meta"
handle = "hide-payment-by-product-meta"
application_url = "https://ddr-tulsa-howard-surgical.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "codeinspire2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ddr-tulsa-howard-surgical.trycloudflare.com/auth/callback",
  "https://ddr-tulsa-howard-surgical.trycloudflare.com/auth/shopify/callback",
  "https://ddr-tulsa-howard-surgical.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
